import turtle


screen = turtle.Screen()
screen.setup(800, 800)
screen.bgcolor('aquamarine')
t = turtle.Turtle()
t.hideturtle()
t2 = turtle.Turtle()
t2.hideturtle()
t3 = turtle.Turtle()
t3.hideturtle()
t4 = turtle.Turtle()
t4.hideturtle()
t.penup()
t.goto(0,90)
t.pendown()
t.write("All About Me", font=("arial", 24, "bold"), align="center")
t.penup()
t.goto(0,40)
t.pendown()
t.write("by: Danielle Schanck", font=("arial", 24, "bold"), align="center")
t.fillcolor('yellow')
t.pensize(3)
t.penup()
t.goto(0,-100)#1/4
t.pendown()
t.begin_fill()
t.goto(50,0)
t.goto(100,-100)
t.goto(0,-100)
t.end_fill()


t2.penup()
turtle.addshape("blackcat.gif")
t2.shape("blackcat.gif")
t2.goto(-100,-100)
a=t2.stamp()

t2.penup()
turtle.addshape("painting.gif")
t2.shape("painting.gif")
t2.goto(170,-80)
b=t2.stamp()

t2.goto(170,-80)




enter = input("Press Enter to Start")
t.clear()
t2.clearstamps()
t2.hideturtle()
screen.bgcolor('pale green')
t.penup()
t.goto(0,90)
t.pendown()
t.write("My Favorite Foods", font=("arial", 24, "bold"), align="center")
t.penup()
t.goto(130, 40)
t.pendown()
t.write("Crunch wraps",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(-90, 40)
t.pendown()
t.write("Olive gardens shrimp alfredo",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(-90, 20)
t.pendown()
t.write("& breadsticks",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(0, -120)
t.pendown()
t.write("pumpkin pie",font=("Calibri",18,"italic"), align ="center")

t.penup()
t.goto(0,150)
t.pensize(3)
t.pencolor('red')
t.fillcolor('green')
t.pendown()
t.begin_fill()
t.circle(25)
t.end_fill()

t2.penup()
turtle.addshape("crunchwrap.gif")
t2.shape("crunchwrap.gif")
t2.goto(145,-35)
a=t2.stamp()

t2.penup()
turtle.addshape("breadsticks.gif")
t2.shape("breadsticks.gif")
t2.goto(-90,-35)
b=t2.stamp()

t3.penup()
turtle.addshape("pie.gif")
t3.shape("pie.gif")
t3.goto(0,-170)
c=t3.stamp()
t3.goto(0,-170)

enter = input("Press Enter to go to next slide")
t.clear()
t2.clearstamps()
t2.hideturtle()
t3.clearstamps()
t3.hideturtle()
screen.bgcolor('pink')
t.pencolor('black')
t.penup()
t.goto(0,120)
t.pendown()
t.write("My Hobbies", font=("arial", 20, "bold"), align="center")
t.penup()
t.goto(90, -120)
t.pendown()
t.write("Playing volleyball",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(-100, 75)
t.pendown()
t.write("hanging out with friends",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(120, 20)
t.pendown()
t.write("online shopping",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(-100, -60)
t.pendown()
t.write("watching movies",font=("Calibri",18,"italic"), align ="center")

t.pensize(3)
t.penup()
t.goto(0, 160)
t.fillcolor('purple')
t.pendown()
t.begin_fill()
t.forward(100)
t.left(90)
t.forward(50)
t.left(90)
t.forward(100)
t.left(90)
t.forward(50)
t.end_fill()

t2.penup()
turtle.addshape("vb.gif")
t2.shape("vb.gif")
t2.goto(140,-175)
a=t2.stamp()

t2.penup()
turtle.addshape("scooter.gif")
t2.shape("scooter.gif")
t2.goto(-90,10)
b=t2.stamp()

t3.penup()
turtle.addshape("amazon.gif")
t3.shape("amazon.gif")
t3.goto(130,-45)
c=t3.stamp()


t4.penup()
turtle.addshape("themovies.gif")
t4.shape("themovies.gif")
t4.goto(-80,-115)
d=t4.stamp()
t4.goto(-80,-130)

enter = input("Press Enter to go to next slide")
t.clear()
t.hideturtle()
t2.clearstamps()
t2.hideturtle()
t3.clearstamps()
t3.hideturtle()
t4.clearstamps()
t4.hideturtle()

screen.bgcolor('dark orange')
t.penup()
t.goto(0,90)
t.pendown()
t.write("My Favorite Movie", font=("arial", 24, "bold"), align="center")
t.penup()

t.goto(0, 65)
t.pendown()
t.write("Terrifier",font=("Calibri",18,"italic"), align ="center")
t.penup()
t.goto(0,160)
t.pensize(3)
t.pencolor('blue')
t.fillcolor('limegreen')
t.pendown()
t.begin_fill()
t.circle(30,180)
t.end_fill()

t.penup()
turtle.addshape("arttoo.gif")
t.shape("arttoo.gif")
t.goto(130,-45)
a=t.stamp()


t2.penup()
turtle.addshape("artluhclown.gif")
t2.shape("artluhclown.gif")
t2.goto(-80,-60)
b=t2.stamp()
t2.goto(-80,-60)

enter = input("Press Enter to go to next slide")
t.clear()
t.hideturtle()
t2.clearstamps()
t2.hideturtle()

screen.bgcolor('medium slate blue')
t.pencolor('black')
t.penup()
t.goto(0,90)
t.pendown()
t.write("My Favorite Sport", font=("arial", 24, "bold"), align="center")
t.penup()

t.goto(0, 65)
t.pendown()
t.write("Volleyball",font=("Calibri",18,"italic"), align ="center")
t.penup()

t.pensize(3)
t.pencolor('purple')
t.fillcolor('green')
t.penup()
t.goto(-70,160)
t.pendown()
t.begin_fill()
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.forward(50)
t.left(45)
t.end_fill()

t3.penup()
turtle.addshape("secondvb.gif")
t3.shape("secondvb.gif")
t3.goto(130,-45)
c=t3.stamp()


t4.penup()
turtle.addshape("vbthree.gif")
t4.shape("vbthree.gif")
t4.goto(-80,-115)
d=t4.stamp()
t4.goto(-80,-130)

turtle.done()
